### ISSUE TITLE
Update title-text of pages.

### ISSUE THREAD

**Issue by sahansk2** [open-source-at-illinois/website-reboot#16]
For some of the pages on https://opensourceatillinois.com/, the title text doesn't match the subpage. These are the pages that have to be updated:
- [ ] Home: Open-Source @ Illinois
- [ ] Announcements: OSAI Announcements
- [ ] Members: OSAI Members

**Comment by sahansk2** [comment]
Apparently, this was a non-issue. The title text was alright the entire time.
http://www.opensourceatillinois.com/

**Comment by itsdell** [comment]
Hello, does title text mean the title from the navigation bar? If that is the case, I would love to take this issue.
