### ISSUE TITLE
SSL missing: https connections aren't set up

### ISSUE THREAD

**Issue by xuxey** [open-source-at-illinois/website-reboot#22]
Looks like SSL isn't set up yet, as https://www.opensourceatillinois.com/ is not served. 
While this is a non-issue for a static page, having https feels more professional. 

[Securing gh-pages with SSL](https://docs.github.com/en/free-pro-team@latest/github/working-with-github-pages/securing-your-github-pages-site-with-https)

**Comment by sahansk2** [comment]
I agree -- it would also be faster, because right now, the website is still being served on HerokuApp, so the Dyno has to wake up everytime somebody tries to visit the website.

The main issue right now is that automatic GitHub pages deployment is not playing nicely with the codebase.

**Comment by sahansk2** [comment]
Closed via resolving #24 .
