### ISSUE TITLE
Update Announcements page to use multiple tries to retrieve announcements

### ISSUE THREAD

**Issue by sahansk2** [open-source-at-illinois/website-reboot#25]
It looks like if the backend wasn't queried in a while, the `/messages` endpoint at `api.opensourceatillinois.com` returns an error. The Announcements page currently only tries to fetch the messages once, and if it fails, the page is stuck on the loading screen.

We should implement some system to try to query `api.opensourceatillinois.com/messages` multiple times on the Announcements page if it fails, and after a certain number of times, an error message is displayed on the website.

**Comment by gprakarsh** [comment]
Added a reload button which allows the user to reload the page after 5 seconds (should be a reasonable amount of time fetch 6 posts).
