### ISSUE TITLE
Develop backend API for Projects Page

### ISSUE THREAD

**Issue by sahansk2** [open-source-at-illinois/website-reboot#4]
According to #1, we would like to fetch four pieces of information:
* Title of project
* Info of project
* Link to project
* Project contributors

We can query the GitHub API for the contributors of a project, since we're assuming that each project has one and only one repository. For all else, we should store this in MongoDB.

**Comment by ghost** [comment]
Hello, I see that nobody has been assigned to this issue yet. Can I try my hand at it?

**Comment by sahansk2** [comment]
@itsdell 
Sure, go for it! When you do go about it, could you put it all into a `backend/` folder in the root of the repository? This is just to make sure Heroku doesn't have any issues with deploying the frontend. 

Be sure to just check out our `CONTRIBUTING.md` for some guidelines. If you have any questions about development or if you're unsure about whether stuff is okay, feel free to reach out to @open-source-at-illinois/executive-board on GitHub or ping `@Exec` on our Discord: https://discord.gg/KkW5QYB!

**Comment by ghost** [comment]
@sahansk2  Thank you!
